export const courses = [
    {
      image: "/topcourses.png",
      title: "Beginner's Guide To Design",
      author: "Ronald Richards",
      rating: 4,
      reviews: 120,
      description: "22 Total Hours. 155 Lectures. Beginner",
      price: 22.99,
    },
    {
      image: "/topcourses.png",
      title: "UX Design Fundamentals",
      author: "Jane Doe",
      rating: 5,
      reviews: 200,
      description: "18 Total Hours. 120 Lectures. Beginner",
      price: 19.99,
    },
    {
      image: "/topcourses.png",
      title: "Frontend Web Development",
      author: "John Smith",
      rating: 4.5,
      reviews: 150,
      description: "30 Total Hours. 180 Lectures. Intermediate",
      price: 29.99,
    },
    {
      image: "/topcourses.png",
      title: "Data Science & Machine Learning",
      author: "Alice Johnson",
      rating: 4.8,
      reviews: 320,
      description: "40 Total Hours. 210 Lectures. Advanced",
      price: 49.99,
    },
    {
      image: "/topcourses.png",
      title: "Full-Stack JavaScript Bootcamp",
      author: "Michael Brown",
      rating: 4.7,
      reviews: 275,
      description: "35 Total Hours. 190 Lectures. Intermediate",
      price: 39.99,
    },
    {
      image: "/topcourses.png",
      title: "Digital Marketing Essentials",
      author: "Sophia Wilson",
      rating: 4.3,
      reviews: 180,
      description: "25 Total Hours. 160 Lectures. Beginner",
      price: 24.99,
    },
    {
      image: "/topcourses.png",
      title: "Cybersecurity for Beginners",
      author: "David Martinez",
      rating: 4.6,
      reviews: 230,
      description: "28 Total Hours. 175 Lectures. Intermediate",
      price: 27.99,
    },
    {
      image: "/topcourses.png",
      title: "Product Management Masterclass",
      author: "Emily Carter",
      rating: 4.9,
      reviews: 400,
      description: "50 Total Hours. 250 Lectures. Advanced",
      price: 59.99,
    },
    {
      image: "/topcourses.png",
      title: "AI & Deep Learning Mastery",
      author: "James Anderson",
      rating: 4.7,
      reviews: 310,
      description: "45 Total Hours. 230 Lectures. Advanced",
      price: 54.99,
    },
  ];